### ISSUE TITLE
テーブル作成

### ISSUE THREAD

**Issue by ryo-1123** [ryo-1123/python_training#3]
### modelsの作成 (objective, target)
```
objectiveはuserと連携
objective {
    'object_name',     CharField max_length=255
    'object_category', CharField max_length=255
}
targetはobjectiveと連携
target {
    'target_name',        CharField max_length=255
    'target_content',   TextField  max_length=1000　←ここでは学習した内容について書いてもらう
    'target_status',     IntegerField (未着手, 進行中, 終了)の3ステータス
    'expectation_time',　DurationField
    'actual_time',      DurationField nullを許容
    'understanding_level', IntegerField (全然, 何となく, 大体わかった, 結構わかった, 完璧)の5ステータス
}
```

**Comment by shimizukawa** [comment]
上記のモデルは、どのようなデータを格納しますか？
実際の値を例示して、仕様をもうすこし明確にする必要がありそうです。

* object_name や target_name は同じ名前が使われても大丈夫でしょうか？
* `_time` の単位はなんでしょうか？
* `target_content` には何を書くのでしょうか？（255文字で足りますか？）

**Comment by ryo-1123** [comment]
@shimizukawa データ型を明記したので確認お願いします。
このアプリをサーバーに上げて複数人が使用することを想定すると、object_nameやtarget_nameは同じ名前が使用されても許容すべきなのかなと思いました。

**Comment by shimizukawa** [comment]
> このアプリをサーバーに上げて複数人が使用することを想定すると、object_nameやtarget_nameは同じ名前が使用されても許容すべきなのかなと思いました。

なるほど、そういうことであれば、 `unique_together` でユーザー毎に一意にすると良いです。
https://docs.djangoproject.com/ja/3.0/ref/models/options/#unique-together

--------

`target_content` については、何が格納されるのかのイメージを知りたいです。
そうしないと、仕様の1000文字の妥当性が分かりません。

意味のあるコードレビューを行うには、コードの善し悪しを見るのでは無く、仕様どおりかを確認するべきす。
そのためには、今回書いてくれたように仕様が明確になっている必要があります。
仕様の妥当性は、要件（どんな文章を入れたいから、等）から決まります。

> 実際の値を例示して

と書いたように、実際に使われるデータを例示してもらうとよさそうです。
それによっては、実は1000文字ではなく TextField が良いのかもしれません。
https://docs.djangoproject.com/ja/3.0/ref/models/fields/#django.db.models.TextField

**Comment by shimizukawa** [comment]
今コードみたらTextFieldにしてますね。
仕様は `CharField` で、実装が `TextField` なので、どちらかが間違えてそうです。
https://github.com/ryo-1123/python_training/blob/3c53bdbc6cf30f576b8a5756dcdf11662410e560/todo_app/targetpage/models.py#L6

**Comment by ryo-1123** [comment]
@shimizukawa  仕様書の修正漏れ、申し訳ありません。修正しておきました。
仕様書の横に少し書きましたが、target_contentには学習した内容をまとめたものを挿入する想定です。ですので、少し大きめにmax_lengthを設定しました。

**Comment by shimizukawa** [comment]
@ryo-1123 修正内容、了解です！

> 実際の値を例示して

これについて補足します。
「実際の値」というのは、「target_contentには学習した内容をまとめたものを挿入する想定」ということを知りたいのではなく（それはそれで重要ですが）、「実際に利用者が書き込む文章例が欲しい」、ということです。
要件としてこの情報があるかどうかで、その後の仕様、設計、実装の妥当性が明確になっていきます。

今回は、この説明で伝わったろうと思うので、OKとします。

**Comment by ryo-1123** [comment]
@shimizukawa ありがとうございます。
次回からモデル作成やテストをしてもらう際には気をつけるよう心掛けます。

**Comment by ryo-1123** [comment]
こちらも実装できたのでクローズします。
